language: ruby
rvm:
  - 2.7.0

install:
  - bundle install
  - gem install jekyll
  - gem install emoji_for_jekyll
  - gem install jekyll-paginate
  - gem install jekyll-gist
  - gem install jekyll-scholar

branches:
  only:
  - master
  
script:
  - JEKYLL_ENV=production 

notifications:
  email:
    recipients:
      jongsukim8@gmail.com
    on_success: always
    on_failure: always

sudo: false
addons:
  opt:
    packages:
      - ncftp
deploy:
  provider: pages
  target_branch: gh-pages
  fqdn: blog.liam.kim
  project_name: blog
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
