title:               Liam Jongsu Kim's Blog
url:                 https://blog.liam.kim
baseurl:             ""

markdown:            kramdown
highlighter:         rouge
lsi:                 false
excerpt_separator:   "\n\n"
incremental:         false

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

sass:
  sass_dir:          _sass
  style:             :compressed

scholar:
  style: modern-language-association
  source: _bibliography

jekyll_get:
  - data: github
    json: 'https://api.github.com/users/appleparan/repos'
    cache: false

author:
  name:              Liam Jongsu Kim
  url:               appleparan.github.io
  email:             jongsukim8@gmail.com

plugins_dir: ./_plugins
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
  - jekyll/scholar
