title:               'Jongsu Liam Kim | Blog'
tagline:             ''
description:         ''
url:                 https://blog.liam.kim
baseurl:             ''

markdown:            kramdown
highlighter:         rouge
lsi:                 false
excerpt_separator:   "\n\n"
incremental:         false

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /blog/:num

moving:
  avatar_url: "images/profile.jpg" # avatar in about page
  about_you:
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

sass:
  sass_dir:          _sass
  style:             :compressed

scholar:
  style: apa
  source: _bibliography

jekyll_get:
  - data: github
    json: 'https://api.github.com/users/appleparan/repos'
    cache: false

author:
  name:              Jongsu Liam Kim
  url:               liam.kim
  email:             jongsukim8@gmail.com

plugins_dir: ./_plugins
plugins:
  - emoji_for_jekyll
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist
  - jekyll/scholar
